include:
  - project: 'trixgo-vn/devops/gitlab-ci-template'
    file: '/.Docker.gitlab-ci.yml'

build-docker:
  extends: .build-docker-template
  variables:
    NODE_OPTIONS: '--max-old-space-size=2048'
  tags:
    - docker
  only:
    refs:
      - master
      - staging
# Click to deploy manual
build-docker-websocket:
  extends: .build-docker-template
  variables:
    _DOCKER_CACHE_IMAGE_TAG: ws-$CI_COMMIT_REF_NAME
    _DOCKER_RELEASE_IMAGE_TAG: ws-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA-$CI_JOB_ID
    NODE_OPTIONS: '--max-old-space-size=2048'
  tags:
    - docker
  only:
    refs:
      - master
      - staging
  when: manual
