POST http://localhost:3003/api/auth/users/login
Content-Type: application/json

{
    "email": "lucdeit1997@gmail.com",
    "password": "1",
    "platform": "1",
    "domain": "https://staging.cbs.trixgo.com"
}

###

POST http://localhost:3003/api/subject_pcm/pcm_plan_tasks/filter
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbmZvVXNlciI6eyJlbWFpbCI6ImhpZXBuaEBwZ2lwYXJ0bmVyLmNvbSIsInBob25lIjoiMDk4NTE5OTI5NSIsImZ1bGxuYW1lIjoiTmd1eeG7hW4gSOG7r3UgSGnhu4dwLVBHSSIsImJpemZ1bGxuYW1lIjoiTmd1eeG7hW4gSOG7r3UgSGnhu4dwLVBHSSIsImNvbXBhbnkiOnsiX2lkIjoiNjA0NmFkZDhiNTU1MjUzNjhiMTA4Y2UyIiwibmFtZSI6IkPDtG5nIHR5IEPhu5UgcGjhuqduIFBHSSBQYXJ0bmVycyIsInNpZ24iOiJQR0kiLCJpbWFnZSI6IjVhNGIwZWU1LTUzNDctNDc5NS04MzBhLTNlNDQ2ZjNhNjIzZC5wbmcifSwiZGVwYXJ0bWVudCI6eyJfaWQiOiI2MDc4YzdkNDk4NGJlMjM2ZDBiYThhMmUiLCJuYW1lIjoiQkFOIEzDg05IIMSQ4bqgTyIsInNpZ24iOiJQR0kuQkxEIn0sImltYWdlIjoiMzIyMmM2MWMtZDIwNi00NGMyLWFhNWQtYmQzMTU0MDczNDRmLmpwZyIsInNpZ25hdHVyZSI6Ijk5NzQzNjQzLWQ2NWItNDAyNS1iNTYyLTZjNTE0N2RmMzM4OC5wbmciLCJzdGF0dXMiOjEsImxldmVsIjowLCJfaWQiOiI2MDc4MTAyYTEyODM1MDIyNTBmOGJhMTIifSwiaWF0IjoxNjUwMzQzODYyfQ.BHRVNMbP7Z9Vqy8g4wykftHbfy0heSmhmpvphjRlcF0

{
    "limit": "2",
    "select": "_id name sign author assignee related"
}

###

GET http://localhost:3003/api/chatting/conversations/get-score-statistics-nps
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbmZvVXNlciI6eyJlbWFpbCI6InZ1aHV5bmhtaW5oOTIyMUBnbWFpbC5jb20iLCJwaG9uZSI6IjA4Mjg5MTI0OTEiLCJmdWxsbmFtZSI6IlbFqSBIdeG7s25oIE1pbmgtVFJYIiwiYml6ZnVsbG5hbWUiOiJWxakgSHXhu7NuaCBNaW5oLVRSWCIsImNvbXBhbnkiOnsiX2lkIjoiNWU2MGRmZmIyYzQzYTQ0NGM1ZjhlMjI3IiwibmFtZSI6IkPDtG5nIHR5IEPhu5UgcGjhuqduIFRyaXhnbyIsInNpZ24iOiJUUlgiLCJpbWFnZSI6IjY3Mjk4ZGIyZGJjNjdiZDgyNmMxN2M1MzI3MWIxMjRjLnBuZyJ9LCJkZXBhcnRtZW50Ijp7Il9pZCI6IjVlODQ3MTgwZDdlMzQ5MGJlNTlhZWY3NSIsIm5hbWUiOiJQSMOSTkcgUEjDgVQgVFJJ4buCTiBT4bqiTiBQSOG6qE0iLCJzaWduIjoiVFJYLlBQVFNQIiwiaW1hZ2UiOiJiOTE4ZDgyMWRjYTA1Mjg5OTdhZTg0OTYwMGQ5ZjY4Yy5qcGcifSwiaW1hZ2UiOiJkNDNmNmFiNi0wMDhlLTQ1YmQtODg0OS0xZWMwOWFiZGJiNWMuanBnIiwic2lnbmF0dXJlIjoic2lnbmF0dXJlX2RlZmF1bHQucG5nIiwic3RhdHVzIjoxLCJsZXZlbCI6MSwiX2lkIjoiNWY5MGVkMGQ1ZTg0MmI3YzE4ZGZmOTcyIn0sImlhdCI6MTY1NDMxMjUwNX0.cj-S340yiEQNzPQVmyJbab19vwx1GNFY-ELH3Q3D07Q

{
    "conversationID": "5e68f9cc143ab46a7bcaf911",
    "messageID": "629ec2dfffb92f0b4baca3c1"
}

###

GET http://localhost:3003/api/chatting/conversations/get-reason-statistics-nps
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbmZvVXNlciI6eyJlbWFpbCI6InZ1aHV5bmhtaW5oOTIyMUBnbWFpbC5jb20iLCJwaG9uZSI6IjA4Mjg5MTI0OTEiLCJmdWxsbmFtZSI6IlbFqSBIdeG7s25oIE1pbmgtVFJYIiwiYml6ZnVsbG5hbWUiOiJWxakgSHXhu7NuaCBNaW5oLVRSWCIsImNvbXBhbnkiOnsiX2lkIjoiNWU2MGRmZmIyYzQzYTQ0NGM1ZjhlMjI3IiwibmFtZSI6IkPDtG5nIHR5IEPhu5UgcGjhuqduIFRyaXhnbyIsInNpZ24iOiJUUlgiLCJpbWFnZSI6IjY3Mjk4ZGIyZGJjNjdiZDgyNmMxN2M1MzI3MWIxMjRjLnBuZyJ9LCJkZXBhcnRtZW50Ijp7Il9pZCI6IjVlODQ3MTgwZDdlMzQ5MGJlNTlhZWY3NSIsIm5hbWUiOiJQSMOSTkcgUEjDgVQgVFJJ4buCTiBT4bqiTiBQSOG6qE0iLCJzaWduIjoiVFJYLlBQVFNQIiwiaW1hZ2UiOiJiOTE4ZDgyMWRjYTA1Mjg5OTdhZTg0OTYwMGQ5ZjY4Yy5qcGcifSwiaW1hZ2UiOiJkNDNmNmFiNi0wMDhlLTQ1YmQtODg0OS0xZWMwOWFiZGJiNWMuanBnIiwic2lnbmF0dXJlIjoic2lnbmF0dXJlX2RlZmF1bHQucG5nIiwic3RhdHVzIjoxLCJsZXZlbCI6MSwiX2lkIjoiNWY5MGVkMGQ1ZTg0MmI3YzE4ZGZmOTcyIn0sImlhdCI6MTY1NDMxMjUwNX0.cj-S340yiEQNzPQVmyJbab19vwx1GNFY-ELH3Q3D07Q

{
    "conversationID": "5e68f9cc143ab46a7bcaf911",
    "messageID": "629f1e986c59532d5dd3ff5c"
}

###

GET https://api.trixgo.com/api/item/doctypes?type=21
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbmZvVXNlciI6eyJlbWFpbCI6InZ1aHV5bmhtaW5oOTIyMUBnbWFpbC5jb20iLCJwaG9uZSI6IjA4Mjg5MTI0OTEiLCJmdWxsbmFtZSI6IlbFqSBIdeG7s25oIE1pbmgtVFJYIiwiYml6ZnVsbG5hbWUiOiJWxakgSHXhu7NuaCBNaW5oLVRSWCIsImNvbXBhbnkiOnsiX2lkIjoiNWU2MGRmZmIyYzQzYTQ0NGM1ZjhlMjI3IiwibmFtZSI6IkPDtG5nIHR5IEPhu5UgcGjhuqduIFRyaXhnbyIsInNpZ24iOiJUUlgiLCJpbWFnZSI6IjY3Mjk4ZGIyZGJjNjdiZDgyNmMxN2M1MzI3MWIxMjRjLnBuZyJ9LCJkZXBhcnRtZW50Ijp7Il9pZCI6IjVlODQ3MTgwZDdlMzQ5MGJlNTlhZWY3NSIsIm5hbWUiOiJQSMOSTkcgUEjDgVQgVFJJ4buCTiBT4bqiTiBQSOG6qE0iLCJzaWduIjoiVFJYLlBQVFNQIiwiaW1hZ2UiOiJiOTE4ZDgyMWRjYTA1Mjg5OTdhZTg0OTYwMGQ5ZjY4Yy5qcGcifSwiaW1hZ2UiOiJkNDNmNmFiNi0wMDhlLTQ1YmQtODg0OS0xZWMwOWFiZGJiNWMuanBnIiwic2lnbmF0dXJlIjoic2lnbmF0dXJlX2RlZmF1bHQucG5nIiwic3RhdHVzIjoxLCJsZXZlbCI6MSwiX2lkIjoiNWY5MGVkMGQ1ZTg0MmI3YzE4ZGZmOTcyIn0sImlhdCI6MTY1NDMxMjUwNX0.cj-S340yiEQNzPQVmyJbab19vwx1GNFY-ELH3Q3D07Q






# https://mongoosejs.com/docs/populate.html#query-conditions