version: "3"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: cbs_prometheus
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "9090:9090"
    command: ["--enable-feature=otlp-write-receiver"]
    volumes:
      - prometheus-data:/prometheus
      - ./provisioning/prometheus/config.yml:/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: cbs_grafana
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "9091:3000"
    volumes:
      - grafana-data:/var/lib/grafana

networks:
  default:
    name: cbs_micro

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
