const BASE_API = 'facebook'

const CF_ROUTINGS_FACEBOOK = {
  FACEBOOK_CALLBACK: `/${BASE_API}/callback`,

  FACEBOOK_GET_LONG_LIVED_UAT: `/${BASE_API}/long-lived-uat`,
  FACEBOOK_GET_LONG_LIVED_PAT: `/${BASE_API}/long-lived-pat`,
}

exports.CF_ROUTINGS_FACEBOOK = CF_ROUTINGS_FACEBOOK
