const BASE_ACTIONS = 'ACT_FACEBOOK';

const CF_ACTIONS_FACEBOOK = {
    FACEBOOK_CALLBACK               : `${BASE_ACTIONS}_FACEBOOK_CALLBACK`,

    FACEBOOK_GET_LONG_LIVED_UAT     : `${BASE_ACTIONS}_FACEBOOK_GET_LONG_LIVED_UAT`,
    FACEBOOK_GET_LONG_LIVED_PAT     : `${BASE_ACTIONS}_FACEBOOK_GET_LONG_LIVED_PAT`,

    FACEBOOK_SEND_MESSAGE           : `${BASE_ACTIONS}_FACEBOOK_SEND_MESSAGE`,
}

exports.CF_ACTIONS_FACEBOOK = CF_ACTIONS_FACEBOOK;