global:
    scrape_interval: 10s

scrape_configs:
    - job_name: cbs_micro
      scrape_interval: 5s
      static_configs:
          - targets: ['host.docker.internal:3030']

    # - job_name: node-exporter
    #   scrape_interval: 5s
    #   static_configs:
    #     - targets: ['host.docker.internal:9100']
